version: "3.9"
services:
  postgres:
    container_name: Veloce-Postgres-Dev
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_dev_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: Veloce-Redis-Dev
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis_dev_volume:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_dev_volume:
  redis_dev_volume: