#!/usr/bin/env bash

if [[ -v DJANGO_SECRET_KEY ]]; then
    echo "Django_Secret_Key=${DJANGO_SECRET_KEY}" >> /Veloce/veloce/.env
else
    echo "Missing Django's secret key! DJANGO_SECRET_KEY environment variable is not set."
    exit 1;
fi


if [[ -v POSTGRES_DB ]]; then
    echo "Postgres_DB=${POSTGRES_DB}" >> /Veloce/veloce/.env
else
    echo "Missing POSTGRES_DB env var! POSTGRES_DB environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_USER ]]; then
    echo "Postgres_User=${POSTGRES_USER}" >> /Veloce/veloce/.env
else
    echo "Missing POSTGRES_USER env var! POSTGRES_USER environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PASSWORD ]]; then
    echo "Postgres_Password=${POSTGRES_PASSWORD}" >> /Veloce/veloce/.env
else
    echo "Missing POSTGRES_PASSWORD env var! POSTGRES_PASSWORD environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_HOST ]]; then
    echo "Postgres_Host=${POSTGRES_HOST}" >> /Veloce/veloce/.env
else
    echo "Missing POSTGRES_HOST env var! POSTGRES_HOST environment variable is not set."
    exit 1;
fi

if [[ -v POSTGRES_PORT ]]; then
    echo "Postgres_Port=${POSTGRES_PORT}" >> /Veloce/veloce/.env
else
    echo "Missing POSTGRES_PORT env var! POSTGRES_PORT environment variable is not set."
    exit 1;
fi

if [[ -v REDIS_HOST ]]; then
    echo "Redis_Host=${REDIS_HOST}" >> /Veloce/veloce/.env
else
    echo "Missing REDIS_HOST env var! REDIS_HOST environment variable is not set."
    exit 1;
fi

if [[ -v REDIS_PORT ]]; then
    echo "Redis_Port=${REDIS_PORT}" >> /Veloce/veloce/.env
else
    echo "Missing REDIS_PORT env var! REDIS_PORT environment variable is not set."
    exit 1;
fi

VELOCE_FIRST_START_CHECK="VELOCE_FIRST_START"

if [ ! -f $VELOCE_FIRST_START_CHECK ]; then
    touch $VELOCE_FIRST_START_CHECK
    echo 'DO NOT EDIT THIS FILE! THIS IS USED WHEN YOU FIRST RUN VELOCE USING DOCKER!' >> $VELOCE_FIRST_START_CHECK
    python3 manage.py migrate
fi


exec gunicorn veloce.wsgi:application --workers 4 --bind 0.0.0.0:8000